import 'api_client.dart';
import 'settings_service.dart';

/// Simple device model returned by GET /me/devices.
class Device {
  final String id;
  final String name;
  final String location;
  final String lastActive;
  final bool current;

  Device({
    required this.id,
    required this.name,
    required this.location,
    required this.lastActive,
    required this.current,
  });

  factory Device.fromJson(Map<String, dynamic> json) => Device(
    id: json['id'].toString(),
    name: json['name'] ?? 'Appareil inconnu',
    location: json['location'] ?? '',
    lastActive: json['lastActive'] ?? json['last_active'] ?? '',
    current: json['current'] == true,
  );

  Map<String, dynamic> toJson() => {
    'id': id,
    'name': name,
    'location': location,
    'lastActive': lastActive,
    'current': current,
  };
}

/// Simple payment method model returned by GET /me/payment-methods.
class PaymentMethodModel {
  final String id;
  final String last4;
  final String expiry;

  PaymentMethodModel({
    required this.id,
    required this.last4,
    required this.expiry,
  });

  factory PaymentMethodModel.fromJson(Map<String, dynamic> json) =>
      PaymentMethodModel(
        id: json['id'].toString(),
        last4: json['last4'] ?? json['lastFour'] ?? '••••',
        expiry: json['expiry'] ?? '',
      );

  Map<String, dynamic> toJson() => {'id': id, 'last4': last4, 'expiry': expiry};
}

/// Result of POST /me/2fa/setup — a QR code to scan plus a manual fallback
/// secret, generated by the backend (real TOTP secret, not fake data).
class TwoFactorSetup {
  final String qrCodeUrl;
  final String manualSecret;
  TwoFactorSetup({required this.qrCodeUrl, required this.manualSecret});

  factory TwoFactorSetup.fromJson(Map<String, dynamic> json) => TwoFactorSetup(
    qrCodeUrl: json['qrCodeUrl'] ?? json['qr_code_url'] ?? '',
    manualSecret: json['secret'] ?? '',
  );
}

/// ── Endpoint contract (adjust paths to match your actual API) ─────────────
/// GET    /me/settings                -> { notifications, darkMode, language,
///                                          twoFactorEnabled, unusualLoginAlerts,
///                                          locationSharingEnabled, locationMode }
/// PATCH  /me/settings                -> body: partial fields above
/// GET    /me/devices                 -> [Device...]
/// DELETE /me/devices/{id}
/// POST   /me/devices/revoke-others
/// GET    /me/payment-methods         -> [PaymentMethod...]
/// POST   /me/payment-methods         -> body: { number, expiry, cvv } -> PaymentMethod
/// DELETE /me/payment-methods/{id}
/// POST   /me/2fa/setup               -> TwoFactorSetup
/// POST   /me/2fa/verify              -> body: { code } -> 200 on success
/// POST   /me/2fa/disable
/// GET    /me/data-export             -> raw JSON export
/// DELETE /me                         -> delete account
///
/// Every read falls back to the local cache (SettingsService) if the
/// request fails, so the UI keeps working offline. Every write updates the
/// cache immediately (optimistic) and then tries to push it to the server;
/// callers get a bool/throw to decide whether to show a "sync failed" toast.
class SettingsRepository {
  static const _base = '/me';

  // ── Preferences / security toggles ────────────────────────────────────
  static Future<void> refreshFromBackend() async {
    try {
      final data = await ApiClient.instance.get('$_base/settings');
      if (data is! Map) return;
      if (data['notifications'] is bool) {
        await SettingsService.setNotifications(data['notifications']);
      }
      if (data['darkMode'] is bool) {
        await SettingsService.setDarkMode(data['darkMode']);
      }
      if (data['language'] is String) {
        await SettingsService.setLanguage(data['language']);
      }
      if (data['twoFactorEnabled'] is bool) {
        await SettingsService.setTwoFactor(data['twoFactorEnabled']);
      }
      if (data['unusualLoginAlerts'] is bool) {
        await SettingsService.setUnusualLoginAlerts(data['unusualLoginAlerts']);
      }
      if (data['locationSharingEnabled'] is bool) {
        await SettingsService.setLocationSharing(
          data['locationSharingEnabled'],
        );
      }
      if (data['locationMode'] is String) {
        final mode = LocationAccessMode.values.firstWhere(
          (m) => m.name == data['locationMode'],
          orElse: () => LocationAccessMode.whileUsing,
        );
        await SettingsService.setLocationMode(mode);
      }
    } catch (_) {
      // Offline / backend unavailable: keep whatever is cached locally.
    }
  }

  static Future<bool> _patchSetting(String key, dynamic value) async {
    try {
      await ApiClient.instance.patch('$_base/settings', body: {key: value});
      return true;
    } catch (_) {
      return false;
    }
  }

  static Future<bool> setNotifications(bool v) async {
    await SettingsService.setNotifications(v);
    return _patchSetting('notifications', v);
  }

  static Future<bool> setDarkMode(bool v) async {
    await SettingsService.setDarkMode(v);
    return _patchSetting('darkMode', v);
  }

  static Future<bool> setLanguage(String code) async {
    await SettingsService.setLanguage(code);
    return _patchSetting('language', code);
  }

  static Future<bool> setUnusualLoginAlerts(bool v) async {
    await SettingsService.setUnusualLoginAlerts(v);
    return _patchSetting('unusualLoginAlerts', v);
  }

  static Future<bool> setLocationSharing(bool v) async {
    await SettingsService.setLocationSharing(v);
    return _patchSetting('locationSharingEnabled', v);
  }

  static Future<bool> setLocationMode(LocationAccessMode mode) async {
    await SettingsService.setLocationMode(mode);
    await SettingsService.setLocationSharing(mode != LocationAccessMode.never);
    return _patchSetting('locationMode', mode.name);
  }

  // ── 2FA ────────────────────────────────────────────────────────────────
  static Future<TwoFactorSetup> start2FASetup() async {
    final data = await ApiClient.instance.post('$_base/2fa/setup');
    return TwoFactorSetup.fromJson(Map<String, dynamic>.from(data));
  }

  static Future<bool> confirm2FASetup(String code) async {
    try {
      await ApiClient.instance.post('$_base/2fa/verify', body: {'code': code});
      await SettingsService.setTwoFactor(true);
      return true;
    } catch (_) {
      return false;
    }
  }

  static Future<bool> disable2FA() async {
    try {
      await ApiClient.instance.post('$_base/2fa/disable');
      await SettingsService.setTwoFactor(false);
      return true;
    } catch (_) {
      return false;
    }
  }

  // ── Connected devices ─────────────────────────────────────────────────
  static Future<List<Device>> fetchDevices() async {
    try {
      final data = await ApiClient.instance.get('$_base/devices');
      final devices = (data as List)
          .map((e) => Device.fromJson(Map<String, dynamic>.from(e)))
          .toList();
      await SettingsService.setConnectedDevices(
        devices.map((d) => d.toJson()).toList(),
      );
      return devices;
    } catch (_) {
      final cached = await SettingsService.getConnectedDevices();
      return cached.map((e) => Device.fromJson(e)).toList();
    }
  }

  static Future<bool> revokeDevice(String id) async {
    try {
      await ApiClient.instance.delete('$_base/devices/$id');
      return true;
    } catch (_) {
      return false;
    }
  }

  static Future<bool> revokeAllOtherDevices() async {
    try {
      await ApiClient.instance.post('$_base/devices/revoke-others');
      return true;
    } catch (_) {
      return false;
    }
  }

  // ── Payment methods ──────────────────────────────────────────────────
  static Future<List<PaymentMethodModel>> fetchPaymentMethods() async {
    try {
      final data = await ApiClient.instance.get('$_base/payment-methods');
      final methods = (data as List)
          .map((e) => PaymentMethodModel.fromJson(Map<String, dynamic>.from(e)))
          .toList();
      await SettingsService.setPaymentMethods(
        methods.map((m) => m.toJson()).toList(),
      );
      return methods;
    } catch (_) {
      final cached = await SettingsService.getPaymentMethods();
      return cached.map((e) => PaymentMethodModel.fromJson(e)).toList();
    }
  }

  static Future<PaymentMethodModel?> addPaymentMethod({
    required String cardNumber,
    required String expiry,
    required String cvv,
  }) async {
    final data = await ApiClient.instance.post(
      '$_base/payment-methods',
      body: {'number': cardNumber, 'expiry': expiry, 'cvv': cvv},
    );
    if (data is! Map) return null;
    return PaymentMethodModel.fromJson(Map<String, dynamic>.from(data));
  }

  static Future<bool> deletePaymentMethod(String id) async {
    try {
      await ApiClient.instance.delete('$_base/payment-methods/$id');
      return true;
    } catch (_) {
      return false;
    }
  }

  // ── Data export & account deletion ───────────────────────────────────
  static Future<Map<String, dynamic>> fetchDataExport({
    required Map<String, dynamic> localFallback,
  }) async {
    try {
      final data = await ApiClient.instance.get('$_base/data-export');
      if (data is Map) return Map<String, dynamic>.from(data);
      return localFallback;
    } catch (_) {
      return localFallback;
    }
  }

  static Future<bool> deleteAccount() async {
    try {
      await ApiClient.instance.delete(_base);
      return true;
    } catch (_) {
      return false;
    }
  }
}
